######################## default configuration ####################
baseURL = "https://demo.gethugothemes.com/"
languageCode = "vi"
title = "BECOCO | Ben Tre Coconut Company Limited"
defaultContentLanguage = "vi"
publishDir = "docs"
theme = "hargo-hugo"
summaryLength = "20"
paginate = 10
disqusShortname = ""

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  link = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  link = "plugins/slick/slick.css"
  [[params.plugins.css]]
  link = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  link = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  link = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  link = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  link = "plugins/google-map/gmap.js"


############################## navigation ###############################
[menu]
  [[menu.main]]
  name = "Giới thiệu"
  URL = "about/"
  weight = 1

  [[menu.main]]
  name = "Sản phẩm"
  URL = "products/"
  weight = 1

  [[menu.main]]
  name = "Bài viết"
  URL = "blog/"
  weight = 2

  [[menu.main]]
  name = "FAQ"
  URL = "faq/"
  weight = 3

  [[menu.main]]
  name = "Liên hệ"
  URL = "contact/"
  weight = 4

  ############# footer menu #############
  [[menu.footer]]
  name = "Giới thiệu"
  URL = "about/"
  weight = 1

  [[menu.footer]]
  name = "Sản phẩm"
  URL = "products/"
  weight = 1

  [[menu.footer]]
  name = "Bài viết"
  URL = "blog/"
  weight = 2

  [[menu.footer]]
  name = "Câu hỏi thường gặp"
  URL = "faq/"
  weight = 3

  [[menu.footer]]
  name = "Quy định & Điều khoản"
  URL = "terms-conditions/"
  weight = 4

  [[menu.footer]]
  name = "Liên hệ"
  URL = "contact/"
  weight = 5


#################### default parameters ################################
[params]
logo = "images/logo-BECOCO.png"
home = "Trang chủ"
# Meta data
description = "Ben Tre Coconut Company Limited"
author = "Tri Pham-Minh"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
mapLatitude = "51.5223477"
mapLongitude = "-0.1622023"
mapMarker = "images/marker.png"
# Google Analitycs
googleAnalyticsID = "" # Your ID
# Contact Information
mobile = "0908599907"
email = "demo@email.com"
location = "Tp. Bến Tre, tỉnh Bến Tre, Việt Nam"
# copyright
copyright = "| Copyright &copy; 2023 Công ty TNHH MTV BECOCO |"
# Snipcart Credentials
snipcartApiKey = "M2E5YjA3NjMtYzRiYS00YzVjLWEyYWYtNDY5ZDI0OWZhYjg5"
currencySymbol = "VND"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # Product Rating
  # it works with https://rating-widget.com/ , you will get the ID and publicKey after creating your account there.
  [params.rating]
  enable = true
  websiteID = "444334"
  publicKey = "811cf0927332bf51f2e12f84608594ac"

  # Social Site
  [[params.social]]
  icon = "ti-facebook"
  link = "#"

  # [[params.social]]
  # icon = "ti-twitter-alt"
  # link = "#"

  [[params.social]]
  icon = "ti-youtube"
  link = "#"

  # [[params.social]]
  # icon = "ti-instagram"
  # link = "#"

  # [[params.social]]
  # icon = "ti-pinterest"
  # link = "#"

  # Contact Form
  [params.contact]
  formAction = "#" # contact form works with formspree.io
